export const INSIGHTS_DATA = {
  articles: [
    {
      id: 'ins001',
      title: 'Bitcoin Halving 2026: Dampak pada Harga dan Miner',
      category: 'Crypto',
      readTime: 4,
      summary: 'Event halving Bitcoin yang diperkirakan terjadi April 2026 akan memangkas reward miner dari 3.125 BTC menjadi 1.5625 BTC...',
      content: `Event halving Bitcoin yang diperkirakan terjadi April 2026 akan memangkas reward miner dari 3.125 BTC menjadi 1.5625 BTC. Secara historis, setiap halving diikuti rally signifikan 12–18 bulan setelahnya.\n\nData on-chain menunjukkan akumulasi besar-besaran oleh whale wallet dalam 3 bulan terakhir. Supply exchange terus menurun, sinyal bullish jangka menengah.\n\n**Analisis Teknikal:** BTC saat ini menguji resistensi $39,000. Breakout bersih akan membuka potensi ke $45,000–$48,000. Support kuat di $36,500.\n\n**Risiko:** Regulasi crypto di AS dan Eropa masih menjadi ketidakpastian utama.`,
      relatedAssets: ['BTC'],
      publishedAt: '2026-03-12T10:00:00Z',
      hasDirectBuy: true, buyAssetTicker: 'BTC',
      tags: ['halving', 'bitcoin', 'macro'],
      author: 'Tim Riset NanoInvest',
    },
    {
      id: 'ins002',
      title: 'NVDA: Raja AI Chips yang Belum Terhentikan',
      category: 'US Stocks',
      readTime: 5,
      summary: 'NVIDIA terus memimpin revolusi AI dengan dominasi H100/H200 GPU. Permintaan dari hyperscaler (Microsoft, Google, Meta) masih jauh melebihi suplai...',
      content: `NVIDIA terus memimpin revolusi AI dengan dominasi H100/H200 GPU. Permintaan dari hyperscaler masih jauh melebihi suplai, memberikan pricing power luar biasa.\n\nRevenue data center tumbuh 409% YoY di Q3 FY2025. Guidance ke depan sangat kuat dengan backlog order masif.\n\n**Valuasi:** P/E forward 35x, premium vs sejarah tapi justified oleh growth profile unik.\n\n**Target Analis:** Konsensus $950, upside +8% dari harga saat ini.`,
      relatedAssets: ['NVDA'],
      publishedAt: '2026-03-11T09:30:00Z',
      hasDirectBuy: true, buyAssetTicker: 'NVDA',
      tags: ['AI', 'semiconductor', 'growth'],
      author: 'Tim Riset NanoInvest',
    },
    {
      id: 'ins003',
      title: 'Emas 2026: Safe Haven di Tengah Ketidakpastian Global',
      category: 'Gold',
      readTime: 3,
      summary: 'Bank sentral global terus akumulasi emas sebagai diversifikasi reserve. Ketegangan geopolitik dan potensi pelemahan USD menjadi katalis...',
      content: `Bank sentral global, terutama dari negara-negara BRICS, terus meningkatkan alokasi emas dalam cadangan devisa mereka. Tren ini sudah berlangsung sejak 2022 dan belum menunjukkan tanda melambat.\n\nKatalis jangka pendek: Penurunan DXY (Dollar Index) yang mendukung harga emas, dan yield obligasi AS yang mulai turun.\n\n**Target harga:** $2,100–$2,200/troy oz dalam 6 bulan ke depan.`,
      relatedAssets: ['GOLD'],
      publishedAt: '2026-03-10T14:00:00Z',
      hasDirectBuy: true, buyAssetTicker: 'GOLD',
      tags: ['gold', 'safe-haven', 'macro'],
      author: 'Tim Riset NanoInvest',
    },
    {
      id: 'ins004',
      title: 'DCA Strategy: Cara Investasi Cerdas Tanpa Timing Market',
      category: 'Education',
      readTime: 6,
      summary: 'Dollar Cost Averaging (DCA) adalah strategi investasi rutin dengan jumlah tetap, tanpa perlu menebak waktu terbaik untuk masuk...',
      content: `Dollar Cost Averaging (DCA) adalah strategi di mana Anda menginvestasikan jumlah uang yang sama secara berkala, terlepas dari kondisi pasar.\n\nManfaat utama:\n• Menghilangkan tekanan timing market\n• Rata-rata harga beli yang lebih baik\n• Membangun disiplin investasi\n\nContoh: Investasi Rp500.000/minggu di BTC selama 52 minggu akan memberikan rata-rata harga yang jauh lebih optimal dibanding beli sekaligus.\n\n**Fitur Recurring Buy** di app ini memudahkan implementasi DCA secara otomatis.`,
      relatedAssets: ['BTC', 'ETH'],
      publishedAt: '2026-03-09T08:00:00Z',
      hasDirectBuy: false, buyAssetTicker: null,
      tags: ['education', 'DCA', 'strategy'],
      author: 'Nano Academy',
    },
    {
      id: 'ins005',
      title: 'Ethereum Roadmap 2026: Apa yang Perlu Diketahui Investor',
      category: 'Crypto',
      readTime: 4,
      summary: 'Upgrade Ethereum terus berjalan, meningkatkan skalabilitas dan menurunkan biaya gas. Layer 2 ecosystem makin mature...',
      content: `Ethereum terus berkembang dengan roadmap yang jelas. Setelah "The Merge" berhasil, fokus beralih ke peningkatan skalabilitas melalui sharding dan Layer 2 solutions.\n\nEkosistem L2 (Arbitrum, Optimism, Base) sudah memproses lebih banyak transaksi harian dibanding mainnet Ethereum sendiri — bukti adopsi yang nyata.\n\n**ETH Staking:** Yield 4.8% APY dengan risiko relatif rendah dibanding altcoin lain.`,
      relatedAssets: ['ETH'],
      publishedAt: '2026-03-08T11:00:00Z',
      hasDirectBuy: true, buyAssetTicker: 'ETH',
      tags: ['ethereum', 'L2', 'staking'],
      author: 'Tim Riset NanoInvest',
    },
    {
      id: 'ins006',
      title: 'Apa itu Gadai Digital? Pinjam Uang Tanpa Jual Kripto',
      category: 'Education',
      readTime: 3,
      summary: 'Gadai Digital memungkinkan Anda mendapatkan pinjaman IDR dengan menjaminkan aset kripto, tanpa harus menjualnya...',
      content: `Gadai Digital atau Crypto-backed Lending memungkinkan Anda mendapatkan pinjaman tunai (IDR) dengan menjaminkan aset kripto sebagai kolateral.\n\nBagaimana cara kerjanya:\n1. Anda menempatkan kripto (BTC/ETH/BNB) sebagai jaminan\n2. Mendapatkan pinjaman IDR hingga 60% dari nilai jaminan (LTV 60%)\n3. Bayar bunga 0.5%/bulan\n4. Saat pinjaman lunas, kripto Anda kembali\n\nIdeal untuk kebutuhan dana darurat tanpa harus "exit" posisi investasi Anda.`,
      relatedAssets: ['BTC', 'ETH'],
      publishedAt: '2026-03-07T10:00:00Z',
      hasDirectBuy: false, buyAssetTicker: null,
      tags: ['education', 'gadai', 'DeFi'],
      author: 'Nano Academy',
    },
    {
      id: 'ins007',
      title: 'Obligasi Ritel ORI025: Investasi Aman Berbunga 6.25%',
      category: 'Bonds',
      readTime: 3,
      summary: 'ORI025 menawarkan kupon 6.25% dengan jaminan penuh pemerintah Indonesia. Cocok untuk profil konservatif...',
      content: `ORI025 adalah Obligasi Ritel Indonesia yang diterbitkan langsung oleh Pemerintah RI melalui Kementerian Keuangan. Ini adalah instrumen investasi paling aman dengan garansi penuh negara.\n\nDetail ORI025:\n• Kupon: 6.25%/tahun\n• Pembayaran: Bulanan\n• Tenor: 2 tahun (jatuh tempo 15 Oktober 2027)\n• Minimum investasi: Rp1.000.000\n• Rating: AAA (terbaik)\n\nSangat direkomendasikan untuk porsi defensif portfolio Anda.`,
      relatedAssets: [],
      publishedAt: '2026-03-06T09:00:00Z',
      hasDirectBuy: false, buyAssetTicker: null,
      tags: ['bonds', 'ORI', 'conservative'],
      author: 'Tim Riset NanoInvest',
    },
    {
      id: 'ins008',
      title: 'Analisis: Pasar Saham HK di Tengah Pemulihan Ekonomi Tiongkok',
      category: 'HK Stocks',
      readTime: 4,
      summary: 'Stimulus fiskal Tiongkok dan valuasi yang murah membuat saham HK menarik bagi investor dengan risk appetite tinggi...',
      content: `Pasar saham Hong Kong telah mengalami tekanan besar selama 3 tahun terakhir. Namun, valuasi yang sangat murah (Hang Seng P/E di bawah 10x) menarik perhatian investor value global.\n\nKatalis pemulihan: Stimulus fiskal dari Beijing, pemulihan konsumsi domestik Tiongkok, dan potensi relaksasi regulasi sektor teknologi.\n\nRisiko utama: Ketegangan geopolitik AS-China dan perlambatan properti Tiongkok.`,
      relatedAssets: ['0700.HK', '9988.HK'],
      publishedAt: '2026-03-05T12:00:00Z',
      hasDirectBuy: false, buyAssetTicker: null,
      tags: ['HK', 'china', 'value-investing'],
      author: 'Tim Riset NanoInvest',
    },
  ],
  categories: ['Semua', 'Crypto', 'US Stocks', 'Gold', 'HK Stocks', 'Bonds', 'Education'],
  academy: [
    { id: 'ac001', title: 'Apa itu DCA?', level: 'beginner', duration: 5 },
    { id: 'ac002', title: 'Memahami P&L dalam Investasi', level: 'beginner', duration: 7 },
    { id: 'ac003', title: 'Analisis Teknikal Dasar', level: 'intermediate', duration: 12 },
    { id: 'ac004', title: 'Diversifikasi Portfolio Modern', level: 'intermediate', duration: 10 },
  ],
}
