export const SOCIAL_DATA = {
  posts: [
    {
      id: 'p001',
      author: { id: 'u002', name: 'Budi Santoso', handle: '@budi_invest', tier: 'platinum' },
      content: 'BTC baru saja menembus $39K! 🚀 Saya sudah akumulasi di range $35–37K. Target berikutnya $42K sebelum halving. #Bitcoin $BTC',
      taggedAssets: ['BTC'],
      timestamp: '2026-03-12T08:15:00Z',
      likes: 142, comments: 23, reposts: 8, isLiked: false, isFollowing: true,
      performanceStats: { totalReturn: 34.2, winRate: 68, followers: 1240 },
    },
    {
      id: 'p002',
      author: { id: 'u003', name: 'Siti Rahayu', handle: '@siti_trader', tier: 'gold' },
      content: 'NVDA terus ATH! Posisi saya dari $650 sekarang sudah +34%. AI boom belum selesai, guys. Keep holding. $NVDA',
      taggedAssets: ['NVDA'],
      timestamp: '2026-03-12T07:45:00Z',
      likes: 89, comments: 14, reposts: 5, isLiked: true, isFollowing: false,
      performanceStats: { totalReturn: 28.7, winRate: 71, followers: 892 },
    },
    {
      id: 'p003',
      author: { id: 'u004', name: 'Ahmad Fauzi', handle: '@ahmad_fx', tier: 'silver' },
      content: 'Alokasi portfolio bulan ini: 40% Crypto, 35% US Stocks, 15% Gold, 10% Cash. Diversifikasi adalah kunci. Emas lagi bagus untuk hedge inflasi. $GOLD',
      taggedAssets: ['GOLD'],
      timestamp: '2026-03-11T18:30:00Z',
      likes: 56, comments: 9, reposts: 3, isLiked: false, isFollowing: false,
      performanceStats: { totalReturn: 18.5, winRate: 62, followers: 445 },
    },
    {
      id: 'p004',
      author: { id: 'u005', name: 'Dewi Kusuma', handle: '@dewi_crypto', tier: 'platinum' },
      content: 'ETH staking APY masih menarik di 4.8%. Passive income sambil hold long term. Lebih baik dari deposito bank 😄 $ETH',
      taggedAssets: ['ETH'],
      timestamp: '2026-03-11T15:20:00Z',
      likes: 203, comments: 41, reposts: 18, isLiked: false, isFollowing: true,
      performanceStats: { totalReturn: 52.1, winRate: 74, followers: 3120 },
    },
    {
      id: 'p005',
      author: { id: 'u006', name: 'Reza Permana', handle: '@reza_quant', tier: 'gold' },
      content: 'Analisis teknikal SOL: RSI di 58, masih ada ruang naik. Support kuat di $175. Risk/reward ratio 1:3 untuk posisi long. $SOL',
      taggedAssets: ['SOL'],
      timestamp: '2026-03-11T12:00:00Z',
      likes: 77, comments: 19, reposts: 6, isLiked: true, isFollowing: false,
      performanceStats: { totalReturn: 41.3, winRate: 69, followers: 1876 },
    },
    {
      id: 'p006',
      author: { id: 'u007', name: 'Putri Handayani', handle: '@putri_growth', tier: 'bronze' },
      content: 'Mulai investasi dari Rp100rb sehari. Sudah 6 bulan konsisten DCA di BTC dan ETH. Hasilnya di luar ekspektasi! Tidak ada kata terlambat untuk mulai 💪',
      taggedAssets: ['BTC', 'ETH'],
      timestamp: '2026-03-10T20:45:00Z',
      likes: 312, comments: 67, reposts: 44, isLiked: false, isFollowing: false,
      performanceStats: { totalReturn: 12.8, winRate: 58, followers: 234 },
    },
    {
      id: 'p007',
      author: { id: 'u008', name: 'Hendra Wijaya', handle: '@hendra_macro', tier: 'platinum' },
      content: 'Fed meeting minggu depan jadi katalis besar. Kemungkinan hold rate 87%. Market sudah price in. Yang menarik: DXY mulai melemah — bullish untuk risk assets dan emas. $GOLD $BTC',
      taggedAssets: ['GOLD', 'BTC'],
      timestamp: '2026-03-10T09:30:00Z',
      likes: 445, comments: 88, reposts: 62, isLiked: false, isFollowing: true,
      performanceStats: { totalReturn: 67.4, winRate: 78, followers: 8920 },
    },
  ],
}
